version: '2'
services:
  activemq:
    container_name: activemq
    image: symptoma/activemq
    #ports:
    #  - "8161:8161"
    #  - "61616:61616"
    #  - "5672:5672"
    network_mode:  "host"
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
      TZ: Asia/Taipei